project:
  type: website
  output-dir: docs
website:
  title: "Feburary Report"
  navbar:
    left:
      - href: weekly report.qmd
        text: Summary of PSM Analysis
      - href: Journal.qmd
        text: Journal Type
format:
  html:
    theme: default
    toc: true

editor: visual
